name: GLuaLint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  Lint:
    uses: CFC-Servers/GLuaFixer/.github/workflows/glualint.yml@feature/add-workflow
    with:
      config: "https://cfc.gg/configs/gluafixer/glualint.json"
